### ISSUE TITLE
Process doesn't exit

### ISSUE THREAD

**Issue by plynchnlm** [requiresafe/grunt-requiresafe#1]
"grunt requiresafe" very quickly reports "(+) No known vulnerabilities found" but then just sits there (for minutes, at least).  I checked top, and its process seems not to be doing anything.  I am using 1.1.1 of grunt-requiresafe and version 0.4.5 of grunt on RedHat (RHEL) 6.7.

**Comment by evilpacket** [comment]
Can you show us your gruntfile for the requiresafe task?

**Comment by evilpacket** [comment]
I found the bug. We'll try and push a fix soon.

**Comment by evilpacket** [comment]
@plynchnlm let me know if v1.1.2 takes care of it for you.

**Comment by plynchnlm** [comment]
Yes, that fixes it.  Thanks for the quick response!
