### ISSUE TITLE
grunt-nsp-shrinkwrap is broken

### ISSUE THREAD

**Issue by pdehaan** [requiresafe/grunt-requiresafe#15]
Looks like https://www.npmjs.com/package/grunt-nsp-shrinkwrap isn't in GitHub anymore, but it's currently breaking and failing all of our Travis builds.

Not sure if there is an easy backwards compatible way to have grunt-nsp-shrinkwrap and grunt-nsp working concurrently.

CUrrent output from grunt-nsp-shrinkwrap && grunt validate-shrinkwrap:

```
➜  fxa-profile-server git:(master) ✗ grunt validate-shrinkwrap
Running "validate-shrinkwrap" task
/Users/pdehaan/dev/fxa-profile-server_pd/fxa-profile-server/npm-shrinkwrap.json
Fatal error: Cannot read property 'patched_versions' of undefined
```

**Comment by evilpacket** [comment]
Sorry yes, the transition is a mess and I apologize for not giving more heads up about the transition. grunt-nsp is the path forward.

The code is available here.  https://github.com/nodesecurity/legacy/tree/master/grunt-nsp-shrinkwrap

One should be able to simply switch out and require nsp read the shrinkwrap and submit. What I don't want is to maintain that going forward as the official lib will be grunt-nsp. If you have another thoughts please let us know.

**Comment by pdehaan** [comment]
@evilpacket I think that's fair (one final minor-ver grunt-nsp-shrinkwrap update [along with the other modules which may currently be broken] which wraps the newer nsp tool/API to keep the old tool running). Then immediately npm deprecate the module and point people to the newer module versions.

Maybe even dump some console output saying "THIS MODULE IS DEPRECATED" when people run the older versions of grunt-nsp-shrinkwrap. Of course, that wouldn't work if people are using exact version numbers for their dependencies instead of semver ranges, but better than nothing.

I tried using the following to see if there were any modules using this as a dependency, but I seem to get 0 results. I'm guessing most projects that use grunt-nsp-shrinkwrap as a dependency are apps and not being submitted to npm.

``` js
var getDependents = require('npm-get-dependents');

getDependents('grunt-nsp-shrinkwrap', function (err, packages) {
  if (err) {
    return console.error(err);
  }
  console.log(packages.length);
  console.log(packages.join('\n'));
});
```

Only interesting results were for the core **nsp** module which had 6 dependencies:

```
bosco
check-build
grunt-fh-build
grunt-nsp
gulp-nsp
mj
```

**Comment by evilpacket** [comment]
Thanks. I'm going to look at this after lunch here and see what I can't figure out.

**Comment by evilpacket** [comment]
@pdehaan Take a look at the quick and dirty https://github.com/nodesecurity/legacy/tree/backport

**Comment by pdehaan** [comment]
I haven't tested it locally, but looks good.
Not sure if you still need `package` here or if @nlf fixed that in https://github.com/nodesecurity/nsp/issues/50

``` js
var payload = {
    package: {name: 'grunt-nsp-shrinkwrap-placeholder'},
    shrinkwrap: require(file)
}
```

Or if you want to pass both, you can grab the `name` property from the shrinkwrap file (but would probably mean you'd need to `require()` the shrinkwrap file to a variable.

**Comment by evilpacket** [comment]
yeah I was just stubbing out the name thing as I had not had a chance to see if that was changed or not yet.

**Comment by evilpacket** [comment]
- grunt-nsp-shrinkwrap@0.1.0 

Should work for now. I'll probably add in some default behavior to the other grunt-nsp that makes it easier to migrate to from this.
