### ISSUE TITLE
Add option to specify reporter

### ISSUE THREAD

**Issue by pdehaan** [requiresafe/grunt-requiresafe#4]
Current output for mozilla/fxa-content-server repo is ~188 lines of output (which is a lot for our Travis logs).

**Comment by evilpacket** [comment]
+1 to this. We'll add it to the stack.

**Comment by pdehaan** [comment]
@evilpacket Is this module an updated version of **grunt-nsp-shrinkwrap**, or **grunt-requiresafe**?

We were currently hit by https://github.com/mozilla/fxa-content-server/issues/3237 which seemed a bit odd. Not sure if it was backed API changes, but still. Not sure if there would be a way to patch **grunt-nsp-shrinkwrap** to not break for everybody globally while still working here.

**Comment by evilpacket** [comment]
@pdehaan this is the replacement to those modules at this point in time.

**Comment by evilpacket** [comment]
I'm going to try and get to this on the plane that I'm just stepping onto. Will be unavailable for a bit.

**Comment by evilpacket** [comment]
I have a fix for this. Once I find internet I'll submit a pr

**Comment by evilpacket** [comment]
Fixed by grunt-nsp@2.1.0
