### ISSUE TITLE
Add option to specify module/advisory exceptions

### ISSUE THREAD

**Issue by pdehaan** [requiresafe/grunt-requiresafe#5]
Not sure if this is the renamed **grunt-requiresafe** module.

It'd also be nice if we could ignore certain advisories, a la: https://www.npmjs.com/package/requiresafe#exceptions

I haven't checked to see if it currently supports an `.requiresaferc` file (or if that file would be renamed to `.nsprc` for consistency), but ideally we'd be able to specify it in the grunt task options as well.

**Comment by evilpacket** [comment]
.nsprc will be honored by grunt-nsp since it uses the cli as the library under the hood.

https://www.npmjs.com/package/nsp#exceptions will work. If you have feedback on this and how it could work better please let us know.

**Comment by pdehaan** [comment]
Not sure what other options are available in an .nsprc file, but it'd be nice if there was a way to hardcode each of those options via Grunt rather than having to add more dotfiles to our top level repo.
