### ISSUE TITLE
Weird behavior if you try and set "package" to a string instead of object

### ISSUE THREAD

**Issue by pdehaan** [requiresafe/grunt-requiresafe#8]
I was quickly testing the module behavior if I just specified the path to package.json and npm-shrinkwrap.json without the `grunt.file.readJSON()` and noticed that it says:

> #### _(+) Error: Cannot find module 'package.json'_

... but then exits with a status code of 0. We should probably use a non-zero status code so a mis-configuration doesn't cause Travis-CI to pass even though no checks have actually been done.

``` sh
$ grunt nsp
Running "nsp" task
(+) Error: Cannot find module 'package.json'

Done, without errors.


$ echo $?
0


$ cat grunttasks/nsp.js
module.exports = function (grunt) {
  grunt.config('nsp', {
    package: 'package.json',
    shrinkwrap: 'npm-shrinkwrap.json'
  });
};
```

**Comment by evilpacket** [comment]
Thanks for finding all the bugs :)
![](http://cdn.meme.am/instances/57254823.jpg)

**Comment by pdehaan** [comment]
@evilpacket Thanks for the great tools!

![](http://www.reactiongifs.us/wp-content/uploads/2013/06/cheers_leonardo_dicaprio.gif)

**Comment by evilpacket** [comment]
With the latest version 2.1.0 it properly calls the callback with the error and doesn't lie to you that everything is ok. We can probably clean up the error a bit for usability.

**Comment by nlf** [comment]
i'm going to close this since we return an error correctly now
